# Generated by Django 4.2.1 on 2023-05-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_job_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'verbose_name': 'Job Category', 'verbose_name_plural': 'Job Categories'},
        ),
    ]
