# Generated by Django 4.2.1 on 2023-05-25 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_jobapplication_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'verbose_name': 'Job Application', 'verbose_name_plural': 'Job Applications'},
        ),
    ]
