# Generated by Django 4.2.1 on 2023-07-01 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': [('can_post_jobs', 'Can add new job posts')], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
    ]
